FLAGS = -ansi -Wall -Wextra -Werror -pedantic-errors
LIBS = -lm

all: cluster
clean:
	rm -rf *.o cluster

cluster: /*all the c files to write like: algo_2.o */
	gcc /*cov.o eigen.o*/ -o cluster $(LIBS)

algo_2.o: algo_2.c BHatMatrix.h stack.h functions.h
	gcc $(FLAGS) -c algo_2.c

stack.o: stack.c stack.h
	gcc $(FLAGS) -c stack.c 
	


